## DEFINE BASE IMAGE
FROM python:3.11.0-slim-buster

## DEFINE & PREPARE ENVIRONMENT
ENV LANG C.UTF-8
ENV LC_ALL C.UTF-8
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONFAULTHANDLER 1
ENV PROJECT_DIR /app

## INSTALL PIPENV
RUN pip install pipenv

## SET WORKING DIRECTORY
WORKDIR ${PROJECT_DIR}

## INCLUDE PIPFILE AND INSTALL
COPY Pipfile Pipfile.lock ${PROJECT_DIR}/
RUN pipenv install --system --deploy && \
    rm Pipfile Pipfile.lock

## DEFINE FLASK ENVIRONMENT
ENV FLASK_APP=example
ENV FLASK_DEBUG=1
ENV FLASK_RUN_PORT=8080
ENV FLASK_RUN_HOST=0.0.0.0

## INCLUDE APPLICATION
COPY example ${PROJECT_DIR}/example

## DEFINE EXPOSED PORT
EXPOSE 8080

## START FLASK APPLICATION (DEV ONLY)
CMD [ "flask", "run" ]
